# Generated by Django 5.1 on 2024-10-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
