# Generated by Django 5.1 on 2024-10-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_bookinstance_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
